-- CREATE DATABASE
CREATE DATABASE [Fok_Deliveries]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fok_Deliveries', FILENAME = N'/var/opt/mssql/data/Fok_Deliveries.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fok_Deliveries_log', FILENAME = N'/var/opt/mssql/data/Fok_Deliveries_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Fok_Deliveries] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Fok_Deliveries] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET ARITHABORT OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Fok_Deliveries] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Fok_Deliveries] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Fok_Deliveries] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Fok_Deliveries] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Fok_Deliveries] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Fok_Deliveries] SET  READ_WRITE 
GO
ALTER DATABASE [Fok_Deliveries] SET RECOVERY FULL 
GO
ALTER DATABASE [Fok_Deliveries] SET  MULTI_USER 
GO
ALTER DATABASE [Fok_Deliveries] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Fok_Deliveries] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Fok_Deliveries] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Fok_Deliveries]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Fok_Deliveries]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Fok_Deliveries] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
CREATE LOGIN [deliverySvc] WITH PASSWORD=N'PasswordDelivery01!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [Fok_Deliveries]

-- LOGIN
GO
USE [Fok_Deliveries]
GO
CREATE USER [deliverySvc] FOR LOGIN [deliverySvc]
GO
USE [Fok_Deliveries]
GO
ALTER ROLE [db_datareader] ADD MEMBER [deliverySvc]
GO
USE [Fok_Deliveries]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [deliverySvc]
GO
