version: '3.4'

services:
  reti.lab.foodonkontainers.users.api:
    image: caretro/foodonkontainers:usersapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr  
   


  reti.lab.foodonkontainers.restaurants.api:
    image: caretro/foodonkontainers:restaurantsapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    
 


  reti.lab.foodonkontainers.basket.api:
    image: caretro/foodonkontainers:basketapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
 


  reti.lab.foodonkontainers.deliveries.api:
    image: caretro/foodonkontainers:deliveriesapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
 


  reti.lab.foodonkontainers.orders.api:
    image: caretro/foodonkontainers:ordersapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
  

  reti.lab.foodonkontainers.payments.api:
    image: caretro/foodonkontainers:paymentsapi
  


  reti.lab.foodonkontainers.reviews.api:
    image: caretro/foodonkontainers:reviewsapi
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
  


  reti.lab.foodonkontainers.web.spa:
    image: caretro/foodonkontainers:webspa
    ports:
      - "5008:80"
  


  reti.lab.foodonkontainers.gateway.simple:
    image: caretro/foodonkontainers:gatewaysimple
    deploy:
      replicas: 1
    ports:
      - "5000:80"
  

