-- CREATE DATABASE
CREATE DATABASE [Fok_Restaurants]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fok_Restaurants', FILENAME = N'/var/opt/mssql/data/Fok_Restaurants.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fok_Restaurants_log', FILENAME = N'/var/opt/mssql/data/Fok_Restaurants_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Fok_Restaurants] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Fok_Restaurants] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET ARITHABORT OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Fok_Restaurants] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Fok_Restaurants] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Fok_Restaurants] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Fok_Restaurants] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Fok_Restaurants] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Fok_Restaurants] SET  READ_WRITE 
GO
ALTER DATABASE [Fok_Restaurants] SET RECOVERY FULL 
GO
ALTER DATABASE [Fok_Restaurants] SET  MULTI_USER 
GO
ALTER DATABASE [Fok_Restaurants] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Fok_Restaurants] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Fok_Restaurants] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Fok_Restaurants]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Fok_Restaurants]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Fok_Restaurants] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
CREATE LOGIN [restaurantSvc] WITH PASSWORD=N'PasswordRestaurant01!', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [Fok_Restaurants]

-- LOGIN
GO
USE [Fok_Restaurants]
GO
CREATE USER [restaurantSvc] FOR LOGIN [restaurantSvc]
GO
USE [Fok_Restaurants]
GO
ALTER ROLE [db_datareader] ADD MEMBER [restaurantSvc]
GO
USE [Fok_Restaurants]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [restaurantSvc]
GO
